import 'language_provider.dart';

class DashboardLanguage {
  static const Map<String, Map<String, String>> _translations = {
    'vi': {
      // Common
      'dashboard': 'Tổng quan',
      'greeting_morning': 'Chào buổi sáng,',
      'greeting_afternoon': 'Chào buổi chiều,',
      'greeting_evening': 'Chào buổi tối,',
      'today': 'Hôm nay',
      'this_month': 'Tháng này',
      'view_all': 'Xem tất cả',
      'loading': 'Đang tải...',
      'no_data': 'Chưa có dữ liệu',
      'refresh': 'Làm mới',

      // Admin stats
      'active_drivers': 'Tài xế hoạt động',
      'total_vehicles': 'Phương tiện',
      'total_trips': 'Danh sách chuyến',
      'fuel_cost': 'Chi phí xăng dầu',
      'recent_fuel_reports': 'Báo cáo xăng gần đây',
      'manage_drivers': 'Quản lý Tài xế',
      'manage_vehicles': 'Quản lý Phương tiện',
      'fuel_reports': 'Báo cáo Xăng dầu',
      'incidents': 'Sự cố',
      'send_notification': 'Gửi Thông báo',
      'driver': 'Tài xế',
      'liters': 'lít',
      'cost': 'Chi phí',
      'has_note': 'Có ghi chú',
      'pending_review': 'Chờ duyệt',
      'quick_actions': 'Thao tác nhanh',
      'payslips': 'Bảng\nlương',
      'menu_admin_notifications': 'Thông báo Quản trị',
      'menu_fuel_prices': 'Giá xăng dầu',
      'menu_payslips': 'Bảng lương',

      // Driver stats
      'my_trips': 'Chuyến xe\ncủa bạn',
      'dash_pre_trip': 'Kiểm tra xe\n& Đổ xăng',
      'start_trip': 'Bắt đầu\nChuyến đi',
      'report_fuel': 'Báo cáo\nXăng dầu',
      'vehicle_check': 'Kiểm tra\nXe đầu ngày',
      'report_incident': 'Báo cáo\nSự cố',
      'today_trips': 'Chuyến hôm nay',
      'km_today': 'Km hôm nay',
      'ongoing_trip': 'Đang chạy',
      'completed_trips': 'Đã hoàn thành',
      'notifications': 'Thông báo',
      'no_trips_today': 'Chưa có chuyến đi hôm nay',
      'no_notifications': 'Không có thông báo mới',
      'trip_started': 'Chuyến đang chạy',
      'tap_to_end': 'Nhấn để kết thúc',
      'vehicles_ok': 'xe tốt',
      'role_admin': 'Quản trị viên',
      'role_driver': 'Tài xế',

      'admin_tagline': 'Điều hành vận tải gọn gàng, một nơi',
      'admin_metrics': 'Số liệu tổng quan',
      'admin_center': 'Trung tâm quản trị',
      'admin_menu_more': 'Thêm trong menu ⋮',
      'admin_desc_members': 'Tài khoản, duyệt hồ sơ & yêu cầu',
      'admin_desc_vehicles': 'Danh sách xe, đăng kiểm & trạng thái',
      'admin_desc_trips': 'Xem danh sách & lên lịch chuyến',
      'admin_desc_schedule': 'Phân công chuyến cho tài xế',
      'admin_desc_contracts': 'Hợp đồng theo tài xế',
      'admin_desc_notifs': 'Cảnh báo hệ thống cho quản trị',
      'admin_desc_fuel_prices': 'Cập nhật giá nhiên liệu',
      'admin_desc_payslips': 'Bảng lương & khiếu nại',
    },
    'en': {
      'dashboard': 'Dashboard',
      'greeting_morning': 'Good morning,',
      'greeting_afternoon': 'Good afternoon,',
      'greeting_evening': 'Good evening,',
      'today': 'Today',
      'this_month': 'This month',
      'view_all': 'View all',
      'loading': 'Loading...',
      'no_data': 'No data yet',
      'refresh': 'Refresh',

      'active_drivers': 'Active Drivers',
      'total_vehicles': 'Vehicles',
      'total_trips': 'Trip list',
      'fuel_cost': 'Fuel Cost',
      'recent_fuel_reports': 'Recent Fuel Reports',
      'manage_drivers': 'Manage Drivers',
      'manage_vehicles': 'Manage Vehicles',
      'fuel_reports': 'Fuel Reports',
      'incidents': 'Incidents',
      'send_notification': 'Send Notification',
      'driver': 'Driver',
      'liters': 'liters',
      'cost': 'Cost',
      'has_note': 'Has note',
      'pending_review': 'Pending review',
      'quick_actions': 'Quick Actions',
      'payslips': 'Salary\nslip',
      'menu_admin_notifications': 'Admin notifications',
      'menu_fuel_prices': 'Fuel prices',
      'menu_payslips': 'Payslips',

      'my_trips': 'Your\ntrips',
      'dash_pre_trip': 'Vehicle check\n& Refuel',
      'start_trip': 'Start\nTrip',
      'report_fuel': 'Report\nFuel',
      'vehicle_check': 'Vehicle\nChecklist',
      'report_incident': 'Report\nIncident',
      'today_trips': "Today's Trips",
      'km_today': 'Km Today',
      'ongoing_trip': 'Ongoing',
      'completed_trips': 'Completed',
      'notifications': 'Notifications',
      'no_trips_today': 'No trips today',
      'no_notifications': 'No new notifications',
      'trip_started': 'Trip in progress',
      'tap_to_end': 'Tap to end',
      'vehicles_ok': 'vehicles OK',
      'role_admin': 'Administrator',
      'role_driver': 'Driver',

      'admin_tagline': 'Run your fleet from one place',
      'admin_metrics': 'Overview metrics',
      'admin_center': 'Admin hub',
      'admin_menu_more': 'More in ⋮ menu',
      'admin_desc_members': 'Accounts, approvals & requests',
      'admin_desc_vehicles': 'Fleet list, registration & status',
      'admin_desc_trips': 'View trips & schedule new ones',
      'admin_desc_schedule': 'Assign trips to drivers',
      'admin_desc_contracts': 'Contracts by driver',
      'admin_desc_notifs': 'System alerts for admins',
      'admin_desc_fuel_prices': 'Fuel price updates',
      'admin_desc_payslips': 'Payslips & disputes',
    },
  };

  static String get(String key, AppLanguage language) {
    final langCode = language == AppLanguage.vi ? 'vi' : 'en';
    return _translations[langCode]?[key] ?? key;
  }
}
