import 'language_provider.dart';

/// Strings for trips, fuel reports, and vehicle checklists (driver + admin).
class OperationsLanguage {
  static const Map<String, Map<String, String>> _t = {
    'vi': {
      'ops_trips_title': 'Chuyến đi',
      'ops_fuel_title': 'Báo cáo xăng dầu',
      'ops_checklist_title': 'Kiểm tra xe',
      'ops_schedule_trip': 'Lên lịch chuyến',
      'ops_admin_fuel': 'Danh sách báo cáo xăng',
      'ops_admin_checklists': 'Checklist xe',
      'ops_admin_vehicle_ops': 'Kiểm tra xe & Báo cáo xăng',
      'ops_admin_trips': 'Danh sách chuyến',
      'save': 'Lưu',
      'submit': 'Gửi',
      'cancel': 'Hủy',
      'refresh': 'Làm mới',
      'loading': 'Đang tải...',
      'error': 'Lỗi',
      'success': 'Thành công',
      'vehicle': 'Xe',
      'select_vehicle': 'Chọn xe',
      'driver': 'Tài xế',
      'select_driver': 'Chọn tài xế',
      'status': 'Trạng thái',
      'scheduled_start': 'Bắt đầu dự kiến',
      'scheduled_end': 'Kết thúc dự kiến',
      'note': 'Ghi chú',
      'decline_note': 'Lý do từ chối',
      'accept': 'Đồng ý',
      'decline': 'Từ chối',
      'start_trip': 'Bắt đầu chạy',
      'end_trip': 'Kết thúc chuyến',
      'start_trip_confirm': 'Xác nhận bắt đầu chuyến đi theo lịch đã nhận?',
      'start_trip_window_hint':
          'Chỉ có thể bắt đầu chạy từ 15 phút trước đến 30 phút sau giờ bắt đầu dự kiến.',
      'checklist_required_before_start':
          'Vui lòng hoàn tất kiểm tra xe cho chuyến này trước khi bắt đầu chạy.',
      'start_odo': 'ODO lúc đi',
      'end_odo': 'ODO lúc về',
      'no_trips': 'Không có chuyến trong khoảng này',
      'report_date': 'Ngày báo cáo',
      'liters': 'Số lít',
      'total_cost': 'Tổng tiền (VNĐ)',
      'receipt_photo': 'Ảnh hóa đơn',
      'odo_photo': 'Ảnh công tơ mét',
      'pick_image': 'Chọn ảnh',
      'link_trip': 'Gắn chuyến đang chạy',
      'optional': 'Tùy chọn',
      'tire': 'Lốp',
      'lights': 'Đèn',
      'clean': 'Vệ sinh',
      'brake': 'Phanh',
      'oil': 'Dầu',
      'admin_note': 'Ghi chú quản trị',
      'edit_admin_note': 'Sửa ghi chú',
      'filter_date': 'Ngày',
      'filter_vehicle': 'Lọc theo xe',
      'all_vehicles': 'Tất cả xe',
      'checklist_empty': 'Không có checklist',
      'fuel_empty': 'Không có báo cáo',
      'fuel_my_today': 'Báo cáo của tôi hôm nay',
      'schedule_start_future':
          'Thời điểm bắt đầu dự kiến phải trong tương lai.',
      'schedule_end_after_start':
          'Thời điểm kết thúc dự kiến phải sau thời điểm bắt đầu.',
      'ops_pre_trip_hub': 'Kiểm tra xe & đổ xăng',
      'ops_checklist_before_trip': 'Kiểm tra xe trước chuyến',
      'ops_fuel_refuel_section': 'Báo cáo đổ xăng',
      'ops_fuel_refuel_hint':
          'Khi đã mua nhiên liệu: nhập số tiền (VNĐ) và đính kèm ảnh hóa đơn.',
      'ops_select_trip_for_checklist': 'Chọn chuyến để kiểm tra xe',
      'ops_no_trip_for_checklist':
          'Bạn cần nhận lịch (Đồng ý) trước — sau đó mới kiểm tra xe / báo cáo xăng. Vào "Chuyến xe của bạn" để xác nhận lịch.',
      'link_trip_fuel': 'Gắn chuyến (đã nhận / đang chạy)',
      'trip_detail_title': 'Chi tiết chuyến',
      'trip_scheduled_start': 'Bắt đầu di chuyển (dự kiến)',
      'trip_scheduled_end': 'Kết thúc (dự kiến)',
      'trip_actual_start': 'Bắt đầu chạy (thực tế)',
      'trip_actual_end': 'Kết thúc chuyến (thực tế)',
      'trip_map_heading': 'Bản đồ hành trình',
      'trip_map_no_location': 'Chưa có dữ liệu tọa độ cho chuyến này.',
      'trip_map_start': 'Điểm bắt đầu',
      'trip_map_end': 'Điểm kết thúc',
      'trip_map_open_fullscreen': 'Xem bản đồ lớn',
      'trip_map_live_tracking': 'Theo dõi di chuyển',
      'trip_map_tracking_requires_location':
          'Không thể bật theo dõi: vui lòng cấp quyền vị trí.',
      'trip_map_current_location': 'Vị trí hiện tại',
      'trip_action_checklist': 'Kiểm tra xe trước khi chạy',
      'trip_action_fuel': 'Chi phí đổ xăng / dầu',
      'trip_action_incident': 'Báo cáo sự cố trong chuyến',
      'fuel_purchase_time': 'Thời điểm mua',
      'incident_type': 'Loại sự cố',
      'incident_type_accident': 'Tai nạn',
      'incident_type_breakdown': 'Hỏng hóc',
      'incident_type_traffic_ticket': 'Phạt nguội / vi phạm',
      'incident_description': 'Mô tả sự cố (tùy chọn)',
      'incident_photo_optional': 'Đính kèm ảnh minh chứng (tùy chọn)',
      'trip_detail_hint': 'Chạm một chuyến để xem chi tiết và báo cáo.',
      'trip_list_cta': 'Chi tiết',
      'checklist_ok': 'OK',
      'checklist_bad': 'Chưa OK',
      'fuel_purchase_time_not_future':
          'Thời điểm trên hóa đơn không được sau thời điểm hiện tại.',
      'fuel_report_window_hint':
          'Chỉ có thể báo chi phí xăng dầu gắn chuyến từ 15 phút trước đến 30 phút sau giờ bắt đầu dự kiến.',
      'fuel_purchase_time_window':
          'Thời điểm mua phải nằm từ 15 phút trước đến 30 phút sau giờ bắt đầu dự kiến.',
      'end_trip_confirm': 'Xác nhận kết thúc chuyến?',
      'trip_admin_checklists_heading': 'Kiểm tra xe',
      'trip_admin_fuel_heading': 'Báo cáo xăng',
      'checklist_done_for_trip': 'Đã hoàn thành kiểm tra xe (chỉ gửi một lần).',
      'trip_history_title': 'Lịch sử chuyến',
      'trip_fuel_history_heading': 'Xăng dầu',
      'trip_no_checklist_history': 'Không có bản ghi kiểm tra xe.',
      'trip_no_fuel_history': 'Không có báo cáo xăng.',
      'trip_violation_history_heading': 'Vi phạm',
      'trip_no_violation_history': 'Không có báo cáo vi phạm.',
      'trip_cancelled_by_admin': 'Chuyến đã bị hủy bởi quản trị',
      'trip_cancel_time_label': 'Thời điểm hủy',
      'trip_cancel_admin': 'Hủy chuyến',
      'trip_cancel_reason': 'Lý do hủy chuyến',
      'trip_cancel_reason_label': 'Lý do hủy',
      'location_required_for_trip_start':
          'Vui lòng cấp quyền vị trí để bắt đầu chuyến và ghi nhận tọa độ.',
    },
    'en': {
      'ops_trips_title': 'Trips',
      'ops_fuel_title': 'Fuel report',
      'ops_checklist_title': 'Vehicle checklist',
      'ops_schedule_trip': 'Schedule trip',
      'ops_admin_fuel': 'Fuel reports',
      'ops_admin_checklists': 'Vehicle checklists',
      'ops_admin_vehicle_ops': 'Vehicle checks & Fuel reports',
      'ops_admin_trips': 'Trip list',
      'save': 'Save',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'refresh': 'Refresh',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'vehicle': 'Vehicle',
      'select_vehicle': 'Select vehicle',
      'driver': 'Driver',
      'select_driver': 'Select driver',
      'status': 'Status',
      'scheduled_start': 'Scheduled start',
      'scheduled_end': 'Scheduled end',
      'note': 'Note',
      'decline_note': 'Decline reason',
      'accept': 'Accept',
      'decline': 'Decline',
      'start_trip': 'Start trip',
      'end_trip': 'End trip',
      'start_trip_confirm': 'Start this accepted scheduled trip now?',
      'start_trip_window_hint':
          'You can start from 15 minutes before through 30 minutes after the scheduled start.',
      'checklist_required_before_start':
          'Complete the vehicle checklist for this trip before starting.',
      'start_odo': 'Start ODO',
      'end_odo': 'End ODO',
      'no_trips': 'No trips in this range',
      'report_date': 'Report date',
      'liters': 'Liters',
      'total_cost': 'Total (VND)',
      'receipt_photo': 'Receipt photo',
      'odo_photo': 'Odometer photo',
      'pick_image': 'Pick image',
      'link_trip': 'Link in-progress trip',
      'optional': 'Optional',
      'tire': 'Tires',
      'lights': 'Lights',
      'clean': 'Cleanliness',
      'brake': 'Brakes',
      'oil': 'Oil',
      'admin_note': 'Admin note',
      'edit_admin_note': 'Edit note',
      'filter_date': 'Date',
      'filter_vehicle': 'Filter by vehicle',
      'all_vehicles': 'All vehicles',
      'checklist_empty': 'No checklists',
      'fuel_empty': 'No reports',
      'fuel_my_today': 'My reports today',
      'schedule_start_future': 'Scheduled start must be in the future.',
      'schedule_end_after_start':
          'Scheduled end must be after scheduled start.',
      'ops_pre_trip_hub': 'Pre-trip check & refuel',
      'ops_checklist_before_trip': 'Vehicle check before trip',
      'ops_fuel_refuel_section': 'Refuel report',
      'ops_fuel_refuel_hint':
          'After purchase: enter amount (VND) and attach the receipt photo.',
      'ops_select_trip_for_checklist': 'Select a trip for the checklist',
      'ops_no_trip_for_checklist':
          'Accept the trip first — then you can complete the checklist or report fuel. Open "Your trips" to confirm.',
      'link_trip_fuel': 'Link trip (accepted / in progress)',
      'trip_detail_title': 'Trip details',
      'trip_scheduled_start': 'Scheduled start',
      'trip_scheduled_end': 'Scheduled end',
      'trip_actual_start': 'Actual start',
      'trip_actual_end': 'Actual end',
      'trip_map_heading': 'Trip map',
      'trip_map_no_location':
          'No location coordinates available for this trip yet.',
      'trip_map_start': 'Start point',
      'trip_map_end': 'End point',
      'trip_map_open_fullscreen': 'Open full map',
      'trip_map_live_tracking': 'Live tracking',
      'trip_map_tracking_requires_location':
          'Unable to start tracking: please allow location access.',
      'trip_map_current_location': 'Current location',
      'trip_action_checklist': 'Pre-trip vehicle check',
      'trip_action_fuel': 'Fuel expense',
      'trip_action_incident': 'Report incident during trip',
      'fuel_purchase_time': 'Purchase time',
      'incident_type': 'Incident type',
      'incident_type_accident': 'Accident',
      'incident_type_breakdown': 'Breakdown',
      'incident_type_traffic_ticket': 'Traffic ticket',
      'incident_description': 'Incident description (optional)',
      'incident_photo_optional': 'Attach evidence image (optional)',
      'trip_detail_hint': 'Tap a trip for details and reports.',
      'trip_list_cta': 'Details',
      'checklist_ok': 'OK',
      'checklist_bad': 'Not OK',
      'fuel_purchase_time_not_future': 'Receipt time cannot be in the future.',
      'fuel_report_window_hint':
          'Trip-linked fuel can be reported from 15 minutes before through 30 minutes after the scheduled start.',
      'fuel_purchase_time_window':
          'Purchase time must fall within 15 minutes before through 30 minutes after the scheduled start.',
      'end_trip_confirm': 'End this trip now?',
      'trip_admin_checklists_heading': 'Vehicle check',
      'trip_admin_fuel_heading': 'Fuel reports',
      'checklist_done_for_trip':
          'Vehicle check completed (one submission only).',
      'trip_history_title': 'Trip history',
      'trip_fuel_history_heading': 'Fuel',
      'trip_no_checklist_history': 'No vehicle check record.',
      'trip_no_fuel_history': 'No fuel report.',
      'trip_violation_history_heading': 'Violations',
      'trip_no_violation_history': 'No violation reports.',
      'trip_cancelled_by_admin': 'Trip cancelled by admin',
      'trip_cancel_time_label': 'Cancelled at',
      'trip_cancel_admin': 'Cancel trip',
      'trip_cancel_reason': 'Cancellation reason',
      'trip_cancel_reason_label': 'Reason',
      'location_required_for_trip_start':
          'Please allow location access to start the trip and record coordinates.',
    },
  };

  static String get(String key, AppLanguage lang) {
    final code = lang == AppLanguage.vi ? 'vi' : 'en';
    return _t[code]?[key] ?? _t['en']![key] ?? key;
  }
}
